### ISSUE TITLE
Add per line item discount to cart object 

### ISSUE THREAD

**Issue by pukhalski** [netlify/gocommerce-js#15]
Now only the total discount is calculated but sometimes it is handy to show a per item discount, since there could be a fixed amount discount for one item and a percentage for all because of a coupon used.

**Comment by bcomnes** [comment]
https://github.com/netlify/gocommerce/issues/124 Is closed now, do we need changes on the JS side?

**Comment by bcomnes** [comment]
Yes we do! https://github.com/netlify/gocommerce-js/pull/25
